### ISSUE TITLE
zepvil.js.cool redirected you too many times.

### ISSUE THREAD

**Issue by Zepvil** [willin/domain#10]
Hello! I added my domain and it works on vercel but when I try to access it it shows this error: zepvil.js.cool redirected you too many times.

Help appreciated

**Comment by willin** [comment]
make `proxy` off

**Comment by Zepvil** [comment]
@willin editing proxy doesn't work when trying to save (for some reason) so I am just gonna remake the domain

**Comment by willin** [comment]
ok
