### ISSUE TITLE
申请中域名不能撤销或者修改

### ISSUE THREAD

**Issue by lolifamily** [willin/domain#12]
发现问题的时候已经晚了，这个应该加强一下

**Comment by willin** [comment]
你改了我还怎么审核- -

**Comment by willin** [comment]
我基本明天都会审核一遍。这个期间也没必要操作

**Comment by willin** [comment]
以前连审核都没有，就是一些不要脸的人一开始挂了个个人页面然后干不知道什么龌龊东西。

解析最好一成不变，省得不必要的麻烦去监管……

**Comment by lolifamily** [comment]
我是说你还没看到的情况下修改

**Comment by lolifamily** [comment]
而且拒绝后这个域名就报废了

**Comment by willin** [comment]
恩。宁可错杀一千，也不放过一个。不然我整个域名都要被墙了所有人都用不了了。

但如果你有什么需要手动操作的也可以私我

**Comment by Vibred** [comment]
我以为关注了您就能申请5个。。然后一次申请5个，被拒绝了四个。但是被拒的四个占着位置，无法再修改了。

**Comment by willin** [comment]
> 我以为关注了您就能申请5个。。然后一次申请5个，被拒绝了四个。但是被拒的四个占着位置，无法再修改了。

申请前先将规则看一遍。
