### ISSUE TITLE
TXT Verification for Discord

### ISSUE THREAD

**Issue by fakedarkdev** [willin/domain#19]
Hi, I need to add a TXT record to fakedark.js.cool for discord verification

hostname: _discord.fakedarkdev.js.cool

Value:  dh=0f817e9945292eb7eaba294fbba9b6f50d74a885

**Comment by willin** [comment]
https://github.com/willin/domain?tab=readme-ov-file#%E8%A7%84%E5%88%99-rules

Do not use bot service on free domains

**Comment by fakedarkdev** [comment]
It is not a bot service. I just wanted to showcase the website in my profile but discord requires me to create a new DNS record with the following details given and I also attached a screenshot. 
![Screenshot from 2024-02-10 20-56-35](https://github.com/willin/domain/assets/155148519/a67f6b81-f456-4688-9a2d-f7cfd6fe28a6)

**Comment by willin** [comment]
what's this?

**Comment by fakedarkdev** [comment]
Oh, it's just a feature of the discord app that allows me to showcase my social accounts, game accounts, and any domain/subdomain that we own or have. It just showcases the things in our profile and nothing else. You can also add your Github account, Youtube account, Reddit account, etc. to showcase. If there is some difficulty adding the DNS record, you can leave it, it's not that important. Hope you understand what I mean.

**Comment by willin** [comment]
can you give me a screenshot where to find this?


<img width="377" alt="image" src="https://github.com/willin/domain/assets/1890238/5762a4e1-9d0f-40da-8a3c-93c727f39966">

add website to my profile does not need so.

**Comment by fakedarkdev** [comment]
Yeah sure, 
Just go to settings and under the first category, you can see connections
![Screenshot from 2024-02-13 20-45-47](https://github.com/willin/domain/assets/155148519/323eae2a-97ae-4714-bd3d-67672315ee66)
Then click on the arrow labelled View More.
![Screenshot from 2024-02-13 20-45-53](https://github.com/willin/domain/assets/155148519/a5458b6f-4919-4456-bcd9-8e810cce8dfa)
Now select the Globe icon labelled Domain.
![Screenshot from 2024-02-13 20-46-11](https://github.com/willin/domain/assets/155148519/814b69c9-0997-4561-8062-c96b6a25fe69)
Now, add your domain name, and follow the instructions. You can also change the method of verification from DNS Record to HTTPS.

**Comment by willin** [comment]
ok.

added `_discord.fakedarkdev.js.cool`
