### ISSUE TITLE
可以改ns服务器吗 js.cool 域名

### ISSUE THREAD

**Issue by mc-sep** [willin/domain#21]
不给改ns服务器啥都干不了。。

最近我不是在搞newbing的服务器吗，想用newbing.js.cool用作cf的自定义域，他却说要绑定到cf里的才行。。。

还有一个，mc.js.cool里面的b.mc.js.cool是不是改了ns服务器的？如果是，可以告诉我js.cool默认实在那个ns服务器吗，谢谢

**Comment by willin** [comment]
1. 我不确定你是否可以用 Cloudflare 的服务，因为会存在跨账号的限制。
2. 我也不知道你二级域名的 ns 解析会出现什么样的问题，因为我没有设置过。但如果你需要改 ns 服务器，你可以直接把记录发给我，手动帮你修改掉。

**Comment by mc-sep** [comment]
> 1. 我不确定你是否可以用 Cloudflare 的服务，因为会存在跨账号的限制。
> 2. 我也不知道你二级域名的 ns 解析会出现什么样的问题，因为我没有设置过。但如果你需要改 ns 服务器，你可以直接把记录发给我，手动帮你修改掉。

现在不用了，我已经买了域名了，感谢支持

blog.mc-sep.top
