### ISSUE TITLE
域名管理页面出现域名丢失的情况

### ISSUE THREAD

**Issue by Katou-Kouseki** [willin/domain#3]
出现问题页面：https://domain.willin.wang/zh/dashboard

使用域名：js.cool

问题描述：在该页面下创建过三个域名，其中后面创建的两条域名在一段时间后消失。第一条创建的域名的相关解析配置自动回退了，有点类似回档的感觉。
而后再尝试创建两条已经消失的域名，但无法创建。

**Comment by willin** [comment]
能把你创建消失的两条域名发我检查一下嘛。 我看了一下计数器你只创建了一个才对吖

**Comment by willin** [comment]
https://github.com/willin/domain/blob/main/lib/dns.ts#L45

找到原因了。应该是这里，不知道是因为 fetch timeout 还是因为 KV 数据远程读写有缓存。 我再测试一下。

**Comment by willin** [comment]
我将你的两条记录删掉了。重新添加应该就不会出现该问题了

**Comment by Katou-Kouseki** [comment]
> 我将你的两条记录删掉了。重新添加应该就不会出现该问题了

好咧，辛苦大佬！
