### ISSUE TITLE
SSL error | SSL 错误

### ISSUE THREAD

**Issue by DoxrGitHub** [willin/domain#8]
Hello, my site, [realm.sh.gg](https://realm.sh.gg) has an SSL error and I am not able to access the site with https://

`NET::ERR_CERTIFICATE_TRANSPARENCY_REQUIRED`

当您在访问网站时，出现"NET::ERR_CERTIFICATE_TRANSPARENCY_REQUIRED"错误，这意味着网站的SSL证书在颁发时未被正确记录。证书透明度现在是SSL证书的要求，如果证书未被记录，将导致此错误。不幸的是，普通的互联网用户无法修复错误，必须由网站所有者解决，他们需要请求证书颁发机构代表他们重新颁发和记录证书。作为网站所有者，您可以请求SSL证书颁发机构将您的网站名称添加到证书透明度日志中

这是从英语翻译成中文的句子

**Comment by DoxrGitHub** [comment]
Nevermind, you just have to wait.

**Comment by willin** [comment]
done
